In [2]:
import pandas as pd
import numpy as np
import yfinance as yf

In [3]:
# stocks = ['BAC', 'AXP', 'KO', 'VZ', 'MCO', 'USB', 'DVA', 'BK', 'CVX', 'VRSN', 'SHV']
# stocks = ['UAL', 'AAL', 'GE', 'SPY', 'XOM', 'JPM', 'F', 'CSCO', 'NKE', 'SHV']
# stocks = ['UAL', 'AAL', 'GE', 'SPY', 'XOM', 'JPM', 'F', 'CSCO', 'NKE', 'SHV']
stocks = ['UAL', 'AAL', 'GE', 'JPM', 'F', 'CSCO', 'NKE', 'XLY', 'XLP', 'XLE', 'XLF', 'XLV', 'XLI', 'XLB', 'XLK', 'XLU', 'SPY', 'SHV']

In [4]:
info = pd.DataFrame(columns=['desc'])
for stock in stocks:
    info.loc[stock] = stock

In [5]:
# Getting Price information
tickers = list(info.index.values)
df = yf.download(tickers, start="2009-04-30", end="2021-11-30")['Adj Close']

[*********************100%***********************]  18 of 18 completed

In [6]:
df

,AAL,CSCO,F,GE,JPM,NKE,SHV,SPY,UAL,XLB,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY
Date,,,,,,,,,,,,,,,,,,
2009-04-30,3.572990,14.067460,4.166870,69.443184,24.183617,11.179111,103.829643,68.043175,4.920000,19.394516,30.474693,6.923429,16.805010,14.172367,15.467692,16.151886,19.311937,19.530489
2009-05-01,3.780394,14.256774,3.964799,69.662766,23.809874,11.274981,103.771202,68.408981,5.160000,19.439840,31.459879,6.871812,16.990366,14.361336,15.530969,16.576778,19.279999,19.438244
2009-05-04,4.317755,14.198518,4.097191,71.913498,26.228233,11.775668,103.761810,70.736252,5.610000,20.535368,32.718029,7.568666,17.546410,14.624238,15.770020,16.826693,19.599470,20.067177
2009-05-05,4.666571,14.293178,4.076286,71.913498,25.517380,11.718143,103.743004,70.494965,6.220000,20.414486,32.278675,7.458978,17.600470,14.533864,15.636426,16.795460,19.823090,20.058790
2009-05-06,4.713707,14.278619,4.361975,75.042549,27.276199,11.635051,103.752411,71.716972,6.020000,20.497599,33.530144,8.052598,17.878494,14.616020,15.734856,16.695482,19.703285,20.268440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-22,19.629999,54.280144,20.375242,100.861008,163.370743,173.531418,110.440002,464.490082,46.480000,87.673866,54.408321,39.227844,105.271324,168.768265,71.799889,66.736015,131.453201,210.251648
2021-11-23,19.469999,54.976044,20.096676,101.899170,167.277313,171.449921,110.449997,465.105988,46.700001,87.763084,56.080471,39.842480,105.450043,168.379745,72.274467,66.805008,131.592209,208.726273
2021-11-24,19.459999,55.214642,20.146420,102.048904,165.965179,171.330414,110.430000,466.347748,46.730000,87.138618,56.628075,39.753258,105.330902,169.605164,72.056946,66.844437,131.542572,209.154968
2021-11-26,17.750000,54.349735,19.648977,97.666672,160.965149,167.336731,110.430000,455.946747,42.259998,85.641861,54.349655,38.434761,102.481163,165.371017,71.147339,65.799690,131.055969,203.452301
2021-11-29,17.740000,55.433350,19.569386,98.225685,160.269318,169.179184,110.440002,461.539642,42.540001,86.038361,54.662567,38.553722,102.659897,169.505524,71.325310,66.775444,131.413483,206.612701

In [22]:
# Resampling to monthly data and changing dataframe to contain returns not share price.
prices = df.resample('M').last()
returns = prices.pct_change().iloc[1:,:]
returns

,AAL,CSCO,F,GE,JPM,NKE,SHV,SPY,UAL,XLB,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY
Date,,,,,,,,,,,,,,,,,,
2009-05-31,-0.319261,-0.042443,-0.038462,0.065612,0.118182,0.087288,-0.000472,0.058453,-0.054878,0.058433,0.128878,0.139795,0.033547,0.023188,0.050909,0.035590,0.068238,-0.007299
2009-06-30,-0.058140,0.008108,0.055652,-0.123408,-0.075610,-0.088458,0.000599,-0.000654,-0.313978,-0.045372,-0.065489,-0.017856,-0.017042,0.036397,0.001989,0.053716,0.023702,0.002534
2009-07-31,0.205762,0.180161,0.317957,0.143345,0.134762,0.093859,-0.000027,0.074606,0.291536,0.128682,0.053486,0.088703,0.087432,0.081823,0.066551,0.037648,0.059293,0.094887
2009-08-31,0.160409,-0.018628,-0.050000,0.037313,0.124450,-0.022069,0.000436,0.036940,0.512136,0.023695,0.010866,0.129900,0.047738,0.016244,0.012235,0.010021,0.026911,0.035219
2009-09-30,0.382353,0.089815,-0.051316,0.188285,0.008284,0.173584,-0.000009,0.035457,0.479936,0.042217,0.058424,0.019476,0.058338,0.046323,0.033110,0.013780,0.006152,0.053488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-07-31,-0.039132,0.052001,-0.061238,-0.037890,-0.018551,0.084277,0.000000,0.024412,-0.106521,0.020775,-0.083163,-0.004633,0.009375,0.038873,0.022009,0.043334,0.049226,0.010529
2021-08-31,-0.021590,0.065920,-0.065950,0.017471,0.053828,-0.014913,-0.000181,0.029760,-0.004495,0.018924,-0.020045,0.051479,0.011126,0.035593,0.010488,0.038957,0.023156,0.017846
2021-09-30,0.029087,-0.077770,0.086723,-0.021818,0.023382,-0.118429,0.000000,-0.046605,0.022791,-0.071886,0.089315,-0.018425,-0.060798,-0.058400,-0.041392,-0.060932,-0.055184,-0.021408
2021-10-31,-0.064327,0.035240,0.206215,0.017859,0.044131,0.151897,-0.000272,0.070163,-0.030061,0.075970,0.103283,0.072742,0.067968,0.081771,0.035009,0.047433,0.051218,0.120925
2021-11-30,-0.076042,-0.003752,0.157438,-0.061695,-0.050974,0.015422,0.000000,0.011649,-0.078023,0.019737,-0.027319,-0.034029,-0.010527,0.053303,0.012491,0.012554,-0.011134,0.030276

In [23]:
# Getting Excess Returns (SHV is the monthly treasury yield)
excess = returns.subtract(returns['SHV'], axis=0)
excess = excess.drop(columns=['SHV'])

In [24]:
with pd.ExcelWriter('industry_portfolio.xlsx') as writer:
    returns.to_excel(writer, sheet_name='total returns')
    excess.to_excel(writer, sheet_name='excess returns')